In [32]:
import numpy as np
import math

# inserting the limiting value and interval

l_x = float(input("Enter the lower limit of x integral:"))
u_x = float(input("Enter the upper limit of x integral:"))
l_y = float(input("Enter the lower limit of y integral:"))
u_y = float(input("Enter the upper limit of y integral:"))
l_z = float(input("Enter the lower limit of z integral:"))
u_z = float(input("Enter the upper limit of z integral:"))

N = int(input("Enter the interval:"))

h1 = (u_x-l_x)/N
h2 = (u_y-l_y)/N
h3 = (u_z-l_z)/N

# defining function to be ingrated 
def f(x,y,z):
    return x*y*z     #2*x*y+2*x-x**2-2*y**2+72 ##np.exp(x+y)


#  converting the function in the matrix form
f_xy = np.zeros(((N+1,N+1,N+1)))
print(f_xy)


for i in range(0,N+1):
    for j in range(0,N+1):
        for k in range(0,N+1):
            f_xy[i,j,k] = f((l_x+(h1*(i))),(l_y+(h2*(j))),(l_z+(h3*(k))))
print(f_xy)

Enter the lower limit of x integral:1
Enter the upper limit of x integral:2
Enter the lower limit of y integral:1
Enter the upper limit of y integral:2
Enter the lower limit of z integral:1
Enter the upper limit of z integral:2
Enter the interval:6
[[[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 

### Triple integration with simpson 3/8

In [40]:
def triple_integration(z):
    
    # working with the z integral
    xy = np.zeros((N+1,N+1))
    for i in range(0,N+1):
        for j in range(0,N+1):
            for k in range(0,N+1):
                if k==0 or k==N:
                    xy[i,j] = xy[i,j] + z[i,j,k]
                elif k%3==0 and k!=(0 or N):
                    xy[i,j] = xy[i,j] + (2*z[i,j,k])
                else:
                    xy[i,j] = xy[i,j] + (3*z[i,j,k])
                    
                
                # working with the y integral
                x = np.zeros(N+1)
                for m in range(0,N+1):
                    for n in range(0,N+1):
                        if n==0 or n==N:
                            x[m] = x[m] + xy[m,n]
                        elif n%3==0 and n!=(0 or N):
                            x[m] = x[m] + (2*xy[m,n])
                        else:
                            x[m] = x[m] + (3*xy[m,n])
                            
                        
                        # working with the x integral
                        integration = 0  
                        for l in range(0,N+1):
                            if l==0 or l==N:
                                integration = integration + x[l]
                            elif l%3==0 and l!=(0 or N):
                                integration = integration + (2*x[l])
                            else:
                                integration = integration + (3*x[l])
                                
    integration = integration*(((3*h1)/8)*((3*h2)/8)*((3*h3)/8))

    return integration
result = triple_integration(f_xy)
print("The result of the triple integration is:\n",result)

The result of the triple integration is:
 3.375


### Triple integration with combination of trapezoidal, simpson 1/3 and simpson 3/8

In [39]:
def triple_integration(z):
    
    # working with the z integral using trapezoidal method
    xy = np.zeros((N+1,N+1))
    for i in range(0,N+1):
        for j in range(0,N+1):
            for k in range(0,N+1):
                if k==0 or k==N:
                    xy[i,j] = xy[i,j] + z[i,j,k]/2
                else:
                    xy[i,j] = xy[i,j] + z[i,j,k]
                    
                # working with the z integral using simpson 1/3 method  
                x = np.zeros(N+1)
                for m in range(0,N+1):
                    for n in range(0,N+1):
                        if n==0 or n==N:
                            x[m] = x[m] + xy[m,n]
                        elif n%2==0 and n!=(0 or N):
                            x[m] = x[m] + (2*xy[m,n])
                        else:
                            x[m] = x[m] + (4*xy[m,n])
                        
                        # working with the z integral using simpson 3/8 method
                        integration = 0
                        for l in range(0,N+1):
                            if l==0 or l==N:
                                integration = integration + x[l]
                            elif l%3==0 and l!=(0 or N):
                                integration = integration + (2*x[l])
                            else:
                                integration = integration + (3*x[l])
                                
    integration = integration*(((3*h1)/8)*(h2/3)*h3)

    return integration
result = triple_integration(f_xy)
print("The result of the tripple integration is:\n",result)

The result of the tripple integration is:
 3.375
